services:
  - type: web
    name: walkie-talkie
    env: python
    plan: free
    region: oregon
    buildCommand: |
      apt-get update && apt-get install -y \
        portaudio19-dev \
        chromium \
        chromium-driver \
        libnss3 \
        libgconf-2-4 \
        libxss1 \
        libasound2 \
        libatk1.0-0 \
        libatk-bridge2.0-0 \
        libcups2 \
        libdrm2 \
        libgbm1 \
        libgtk-3-0 \
        libnspr4 \
        libpango-1.0-0 \
        ca-certificates \
        fonts-liberation
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: flights_db_hxtv
          property: connectionString
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/google-credentials.json
      - key: PORT
        value: 8080
    autoDeploy: true

databases:
  - name: flights_db_hxtv
    databaseName: flights_db_hxtv
    region: oregon
    plan: free
